baseURL = "https://jeremylongshore.com/"
title = "Jeremy Longshore"
author = "Jeremy Longshore"
copyright = "Copyright Â© 2025, Jeremy Longshore."
languageCode = "en-US"
theme = "hugo-bearblog"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[pagination]
pagerSize = 10

[permalinks]
blog = "/:slug/"
posts = "/posts/:slug/"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "AI engineering, software, and startup notes."
favicon = "images/favicon.png"
images = ["images/share.png"]
title = "Jeremy Longshore"
hideMadeWithLine = false
enablePostNavigator = false
dateFormat = "02 Jan, 2006"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = 'friendly'
    lineNos = false
    lineNumbersInTable = false
    codeFences = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 30